runtime: nodejs16

handlers:
- url: /.*
  script: auto

POSTMARK_API_KEY=
NEXT_MONGODB_URL=
JWT_SECRET=
NEXT_PUBLIC_BASE_URL=http://127.0.0.1:3000/
NEXT_BUSENESS_URL=
NEXT_PUBLIC_GOOGLE_MAP_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_STRIPE_SECRET_KEY=
NEXT_PUBLIC_GCS_STORAGE_PATH=./storage.json
NEXTAUTH_URL=
NEXTAUTH_SECRET=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_TWILIO_ACCOUNT_SID=
NEXT_PUBLIC_TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=